workflows:
  android-native:
    name: Android Native Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set up Gradle
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "lkanth07@gmail.com"

Bash chmod +x gradlew 
