workflows:
  android-app:
    name: Quiksolverai
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: stable
    scripts:
      - name: Set up Flutter
        script: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b $FLUTTER_VERSION
          export PATH="$PATH:pwd/flutter/bin"
          flutter --version
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - "lkanth07@gmail.com"
