workflows:
  android-native:
    name: Android Native Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Reinstall Gradle Wrapper
        script: ./gradlew wrapper --gradle-version 8.0
      - name: Clean project
        script: ./gradlew clean
      - name: Get dependencies
        script: ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "your-lkanth07@gmail.com"
